title: Kishore Billu
logo: "/profile1.png?raw=false" 
description: > # your text below (remove <br> elements if you don't need line breaks)
 Cloud and DevOps Engineer
   <br><br>
  <a href="mailto:bckishore21@gmail.com">bckishore@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/kishorebillu/">LinkedIn Profile</a>
  <br>
  <a href="https://www.credly.com/users/bckishore/">Credly Profile</a>
  <br>

theme: jekyll-theme-minimal
#theme: jekyll-theme-modernist
