title: Kishore Billu
logo: "/profile.jpeg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
 Cloud and DevOps Engineer
   <br><br>
  <a href="mailto:bckishore@gmail.com">bckishore@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/kishorebillu/">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
