title: Kishore Billu
logo: "/profile.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
 Cloud and DevOps Engineer
   <br><br>
  <a href="mailto:bckishore@gmail.com">bckishore@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/kishorebillu/">LinkedIn Profile</a>
  <br>
  <a href="https://www.credly.com/users/bckishore/">Credly Profile</a>
  <br>


  https://www.credly.com/users/bckishore
theme: jekyll-theme-minimal
